In [1]:
import torch

In [5]:
torch.sigmoid(torch.tensor(0.8))

tensor(0.6900)

In [10]:
torch.tensor([  [], [[1,2],[3,4]] , [[1,2]]         ] )

tensor([], size=(3, 0))

In [7]:
torch.tensor([1,2])

tensor([1, 2])

In [11]:
batch_size = 8
numgrid = 7
numbox = 5
num_classes = 13

labelgrid = torch.randn((batch_size, numgrid, numgrid, numbox, 5 + num_classes))

In [12]:
torch.zeros_like(labelgrid[..., 0]).shape

torch.Size([8, 7, 7, 5])

In [13]:
torch.sigmoid(torch.tensor([[0,0,0,0]]))

tensor([[0.5000, 0.5000, 0.5000, 0.5000]])

In [16]:
# 2x3x3x4=
seq = torch.arange(2*3*3*5*4).contiguous()

grid = seq.reshape(2,3,3,5,4)


In [24]:
grid_mask = torch.zeros((2,3,3,1), dtype = torch.int64)

grid_mask + i

tensor([[[[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 

In [35]:
torch.gather(grid, -2, grid_mask.unsqueeze(-1).repeat(1,1,1,1,4))

tensor([[[[[  0,   1,   2,   3]],

          [[ 20,  21,  22,  23]],

          [[ 40,  41,  42,  43]]],


         [[[ 60,  61,  62,  63]],

          [[ 80,  81,  82,  83]],

          [[100, 101, 102, 103]]],


         [[[120, 121, 122, 123]],

          [[140, 141, 142, 143]],

          [[160, 161, 162, 163]]]],



        [[[[180, 181, 182, 183]],

          [[200, 201, 202, 203]],

          [[220, 221, 222, 223]]],


         [[[240, 241, 242, 243]],

          [[260, 261, 262, 263]],

          [[280, 281, 282, 283]]],


         [[[300, 301, 302, 303]],

          [[320, 321, 322, 323]],

          [[340, 341, 342, 343]]]]])

In [19]:
grid[..., 0, :]

tensor([[[[  0,   1,   2,   3],
          [ 20,  21,  22,  23],
          [ 40,  41,  42,  43]],

         [[ 60,  61,  62,  63],
          [ 80,  81,  82,  83],
          [100, 101, 102, 103]],

         [[120, 121, 122, 123],
          [140, 141, 142, 143],
          [160, 161, 162, 163]]],


        [[[180, 181, 182, 183],
          [200, 201, 202, 203],
          [220, 221, 222, 223]],

         [[240, 241, 242, 243],
          [260, 261, 262, 263],
          [280, 281, 282, 283]],

         [[300, 301, 302, 303],
          [320, 321, 322, 323],
          [340, 341, 342, 343]]]])

In [145]:
numgrid = 7

x = torch.arange(numgrid)
y = torch.arange(numgrid)

grid_y, grid_x = torch.meshgrid(x,y, indexing = 'ij')
grid_x = grid_x.expand(8, -1,-1)#.unsqueeze(-1)
grid_y = grid_y.expand(8, -1,-1)#.unsqueeze(-1)

In [147]:
grid_x * torch.randn(8,7,7,1)

RuntimeError: The size of tensor a (8) must match the size of tensor b (7) at non-singleton dimension 1

In [131]:
box1s = labelgrid[..., 0, :]

In [148]:
loss = torch.nn.MSELoss()
inp = torch.randn((16,13,13, 1))
target = torch.randn((16,13,13, 1))
output = loss(inp, target)

In [150]:
output

tensor(1.9788)

In [104]:
ls = torch.tensor([[10, 15],[20, 25],[30, 35],[40, 45],[50, 55]])
h = ls[:,0]
w = ls[:,1]


value = torch.tensor([[0,1],
                      [2,3]])

torch.take(w, value)

        

tensor([[15, 25],
        [35, 45]])

In [101]:
indices = torch.arange(5).repeat(1,5).reshape(5,5)

In [115]:
torch.sqrt(torch.take(ls, indices))

tensor([[3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772]])

In [109]:
(torch.zeros((8,7,7,5,1)) * torch.randn((8,7,7,5))).shape

RuntimeError: The size of tensor a (5) must match the size of tensor b (7) at non-singleton dimension 3

In [122]:
from collections import OrderedDict
from torch import nn
import torch.nn.functional as F
import torch.utils.model_zoo as model_zoo

model_paths = {
    'darknet19': 'https://s3.ap-northeast-2.amazonaws.com/deepbaksuvision/darknet19-deepBakSu-e1b3ec1e.pth'
}

class GlobalAvgPool2d(nn.Module):
    def __init__(self):
        super(GlobalAvgPool2d, self).__init__()

    def forward(self, x):
        N = x.data.size(0)
        C = x.data.size(1)
        H = x.data.size(2)
        W = x.data.size(3)
        x = F.avg_pool2d(x, (H, W))
        x = x.view(N, C)
        return x


class Darknet19(nn.Module):
    def __init__(self, pretrained=True):
        super(Darknet19, self).__init__()

        self.features = nn.Sequential(OrderedDict([
        ('layer1', nn.Sequential(OrderedDict([
            ('conv1_1', nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn1_1', nn.BatchNorm2d(32)),
            ('leaky1_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool1', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer2', nn.Sequential(OrderedDict([
            ('conv2_1', nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn2_1', nn.BatchNorm2d(64)),
            ('leaky2_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool2', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer3', nn.Sequential(OrderedDict([
            ('conv3_1', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_1', nn.BatchNorm2d(128)),
            ('leaky3_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_2', nn.Conv2d(128, 64, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn3_2', nn.BatchNorm2d(64)),
            ('leaky3_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_3', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_3', nn.BatchNorm2d(128)),
            ('leaky3_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool3', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer4', nn.Sequential(OrderedDict([
            ('conv4_1', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_1', nn.BatchNorm2d(256)),
            ('leaky4_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_2', nn.Conv2d(256, 128, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn4_2', nn.BatchNorm2d(128)),
            ('leaky4_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_3', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_3', nn.BatchNorm2d(256)),
            ('leaky4_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool4', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer5', nn.Sequential(OrderedDict([
            ('conv5_1', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_1', nn.BatchNorm2d(512)),
            ('leaky5_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_2', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn5_2', nn.BatchNorm2d(256)),
            ('leaky5_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_3', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_3', nn.BatchNorm2d(512)),
            ('leaky5_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_4', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn5_4', nn.BatchNorm2d(256)),
            ('leaky5_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_5', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_5', nn.BatchNorm2d(512)),
            ('leaky5_5', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool5', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer6', nn.Sequential(OrderedDict([
            ('conv6_1', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_1', nn.BatchNorm2d(1024)),
            ('leaky6_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_2', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn6_2', nn.BatchNorm2d(512)),
            ('leaky6_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_3', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_3', nn.BatchNorm2d(1024)),
            ('leaky6_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_4', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn6_4', nn.BatchNorm2d(512)),
            ('leaky6_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_5', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_5', nn.BatchNorm2d(1024)),
            ('leaky6_5', nn.LeakyReLU(0.1, inplace=True))
        ])))
        ]))

        self.classifier = nn.Sequential(OrderedDict([
        ('conv7_1', nn.Conv2d(1024, 1000, kernel_size=(1, 1), stride=(1, 1))),
        ('globalavgpool', GlobalAvgPool2d()),
        ('softmax', nn.Softmax(dim=1))
        ]))

        # if pretrained:
        #     self.load_state_dict(model_zoo.load_url(model_paths['darknet19'],  progress=True))
        #     print('Model is loaded')

    def forward(self, x):
        for layer in self.features :
            print(layer)
            print('.')
        # out = self.features(x)
        # out = self.classifier(out)
        # return out

In [123]:
model = Darknet19()

In [124]:
model(torch.rand(1))

Sequential(
  (conv1_1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1_1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky1_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv2_1): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2_1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky2_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv3_1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn3_1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky3_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (conv3_2): Conv2d(128, 64, kernel_size=(1, 1), stride=(

In [129]:
torch.zeros_like(torch.randn((8,7,7,5,24))[...,0]).shape

torch.Size([8, 7, 7, 5])

In [3]:
import torch

a = torch.tensor([1]).numpy().item()

a

1

In [6]:
import numpy as np
np.maximum(torch.tensor([1,2,3]), torch.tensor([1,2,3]))

tensor([1, 2, 3])

In [99]:
# from global_utils import IoU

a = np.array([[0.8,0,5,10, 0],
              [0.2,0,10,5, 0],
              [0.5,3,5,10, 1],
              [0.3,0,3,3, 1]])

def nms(predictions : np.ndarray, iou_threshold: float) -> np.ndarray :
    '''
    vectorize nms
    reference : https://blog.roboflow.com/how-to-code-non-maximum-suppression-nms-in-plain-numpy/
    '''
    rows, columns = predictions.shape

    sort_index = np.flip(predictions[:,0].argsort())
    box1ictions = predictions[sort_index]

    boxes = predictions[:, 1:5]
    categories = predictions[:, -1]
    ious = IoU(boxes, boxes)
    ious = ious - np.eye(rows)
    keep = np.ones(rows, dtype = bool)

    for index, (iou, category) in enumerate(zip(ious, categories)) :
        if not keep[index] :
            continue
        
        condition = (iou > iou_threshold) & (categories == category)
        keep = keep & ~condition

    return predictions[keep[sort_index.argsort()]]

In [102]:
nms(a, iou_threshold= 0)

ValueError: step must be greater than zero

In [103]:
a = torch.tensor([[1],
                [2],
                [3],
                [4]])

b = torch.tensor([[5],
            [6],
            [7],
            [8]])

In [106]:
torch.randn((1,3,24,24)).T.shape

C:\Users\user\AppData\Local\Temp\ipykernel_3996\841565123.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3575.)
  torch.randn((1,3,24,24)).T.shape


torch.Size([24, 24, 3, 1])

In [98]:
def IoU(box1, box2) :
    # box = [x,y,w,h]

    def box_area(box) :
        return box[2] * box[3]
    
    box1_area = box_area(box1.T)
    box2_area = box_area(box2.T)

    box1_w = box1[..., 2:3]
    box1_h = box1[..., 3:4]
    box2_w = box2[..., 2:3]
    box2_h = box2[..., 3:4]
    box1_xmin = box1[..., 0:1] - box1_w / 2
    box1_ymin = box1[..., 1:2] - box1_h / 2
    box1_xmax = box1[..., 0:1] + box1_w / 2
    box1_ymax = box1[..., 1:2] + box1_w / 2

    box2_xmin = box2[..., 0:1] - box2_w / 2
    box2_ymin = box2[..., 1:2] - box2_h / 2
    box2_xmax = box2[..., 0:1] + box2_w / 2
    box2_ymax = box2[..., 1:2] + box2_w / 2
    
    box1_topleft = torch.cat([box1_xmin, box1_ymin], axis = -1)
    box2_topleft = torch.cat([box2_xmin, box2_ymin], axis = -1)

    box1_bottomright = torch.cat([box1_xmax, box1_ymax], axis = -1)
    box2_bottomright = torch.cat([box2_xmax, box2_ymax], axis = -1)

    top_left = torch.max(box1_topleft[:,None, :], box2_topleft)
    bottom_right = torch.min(box1_bottomright[:, None, :], box2_bottomright)



    area_inter = torch.prod(
        torch.clip(bottom_right - top_left, min = 0 , max = None), -1)

    return area_inter / (box1_area[:, None] + box2_area - area_inter + 1e-9)

In [107]:
samp = np.array([1,3,5,2,4])

keep = samp > 1

keep

array([False,  True,  True,  True,  True])

In [109]:
np.flip([])

np.array([]).argsort()

array([], dtype=int64)

In [3]:
import torch

samp = torch.zeros((36, 36))

samp.expand(8, -1, -1)

torch.Size([8, 36, 36])

In [2]:
import sys
sys.path.append('./YOLOv2')
from YOLOv2.model import Yolov2



c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


In [11]:
model.load_from_checkpoint(in_channels = 3, anchorbox = [[0.57273, 0.677385], [1.87446, 2.06253], [3.33843, 5.47434], [7.88282, 3.52778], [9.77052, 9.16828]], num_grid = 13, num_classes = 13,
            checkpoint_path = 'YOLOv2/outputs/2023-04-16/12-36-28/tensorboard/yolov2-epoch=72-val_loss=3863.54.ckpt')

c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


RuntimeError: Error(s) in loading state_dict for Yolov2:
	While copying the parameter named "yolo_loss.grid_x", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).
	While copying the parameter named "yolo_loss.grid_y", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).

In [15]:
import torch

model = Yolov2(in_channels = 3, anchorbox = [[0.57273, 0.677385], [1.87446, 2.06253], [3.33843, 5.47434], [7.88282, 3.52778], [9.77052, 9.16828]], num_grid = 13, num_classes = 13)

model.yolo_loss.grid_x = model.yolo_loss.grid_x.contiguous()
model.yolo_loss.grid_y = model.yolo_loss.grid_y.contiguous()

weight = torch.load('YOLOv2/outputs/2023-04-16/12-36-28/tensorboard/yolov2-epoch=72-val_loss=3863.54.ckpt')
model.load_state_dict(weight['state_dict'])

c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


RuntimeError: Error(s) in loading state_dict for Yolov2:
	While copying the parameter named "yolo_loss.grid_x", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).
	While copying the parameter named "yolo_loss.grid_y", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).

In [19]:
import sys
sys.path.append('YOLOv2')
from YOLOv2.data import BDDDataModule

BDDDataModule()


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


     -------------------------------------- 154.5/154.5 kB 9.0 MB/s eta 0:00:00
     -------------------------------------- 117.0/117.0 kB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 79.5/79.5 kB ? eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144578 sha256=0da2085491a6d9450add46c9e94525d78ec7272bd81250e788034e3c6bc6dca4
  Stored in directory: c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\48\6a\c2\acb58c7afdf57e4cddf5e1513f5a2d62aa8e98f82a00c76d7c
Successfully built antlr4-python3-runtime


TypeError: BDDDataModule.__init__() missing 1 required positional argument: 'cfg'

In [34]:
loss = torch.nn.CrossEntropyLoss()

inp = torch.tensor([[0,1,0], [0,0,1], [0,1,0], [0,1,0]]).float()
target = torch.tensor([[1], [2], [1], [1]]).long()
print(inp.shape)
print(target.shape)
loss(inp, target)

torch.Size([4, 3])
torch.Size([4, 1])


RuntimeError: 0D or 1D target tensor expected, multi-target not supported