In [1]:
import torch

In [5]:
torch.sigmoid(torch.tensor(0.8))

tensor(0.6900)

In [10]:
torch.tensor([  [], [[1,2],[3,4]] , [[1,2]]         ] )

tensor([], size=(3, 0))

In [7]:
torch.tensor([1,2])

tensor([1, 2])

In [11]:
batch_size = 8
numgrid = 7
numbox = 5
num_classes = 13

labelgrid = torch.randn((batch_size, numgrid, numgrid, numbox, 5 + num_classes))

In [12]:
torch.zeros_like(labelgrid[..., 0]).shape

torch.Size([8, 7, 7, 5])

In [13]:
torch.sigmoid(torch.tensor([[0,0,0,0]]))

tensor([[0.5000, 0.5000, 0.5000, 0.5000]])

In [16]:
# 2x3x3x4=
seq = torch.arange(2*3*3*5*4).contiguous()

grid = seq.reshape(2,3,3,5,4)


In [24]:
grid_mask = torch.zeros((2,3,3,1), dtype = torch.int64)

grid_mask + i

tensor([[[[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 

In [35]:
torch.gather(grid, -2, grid_mask.unsqueeze(-1).repeat(1,1,1,1,4))

tensor([[[[[  0,   1,   2,   3]],

          [[ 20,  21,  22,  23]],

          [[ 40,  41,  42,  43]]],


         [[[ 60,  61,  62,  63]],

          [[ 80,  81,  82,  83]],

          [[100, 101, 102, 103]]],


         [[[120, 121, 122, 123]],

          [[140, 141, 142, 143]],

          [[160, 161, 162, 163]]]],



        [[[[180, 181, 182, 183]],

          [[200, 201, 202, 203]],

          [[220, 221, 222, 223]]],


         [[[240, 241, 242, 243]],

          [[260, 261, 262, 263]],

          [[280, 281, 282, 283]]],


         [[[300, 301, 302, 303]],

          [[320, 321, 322, 323]],

          [[340, 341, 342, 343]]]]])

In [19]:
grid[..., 0, :]

tensor([[[[  0,   1,   2,   3],
          [ 20,  21,  22,  23],
          [ 40,  41,  42,  43]],

         [[ 60,  61,  62,  63],
          [ 80,  81,  82,  83],
          [100, 101, 102, 103]],

         [[120, 121, 122, 123],
          [140, 141, 142, 143],
          [160, 161, 162, 163]]],


        [[[180, 181, 182, 183],
          [200, 201, 202, 203],
          [220, 221, 222, 223]],

         [[240, 241, 242, 243],
          [260, 261, 262, 263],
          [280, 281, 282, 283]],

         [[300, 301, 302, 303],
          [320, 321, 322, 323],
          [340, 341, 342, 343]]]])

In [145]:
numgrid = 7

x = torch.arange(numgrid)
y = torch.arange(numgrid)

grid_y, grid_x = torch.meshgrid(x,y, indexing = 'ij')
grid_x = grid_x.expand(8, -1,-1)#.unsqueeze(-1)
grid_y = grid_y.expand(8, -1,-1)#.unsqueeze(-1)

In [147]:
grid_x * torch.randn(8,7,7,1)

RuntimeError: The size of tensor a (8) must match the size of tensor b (7) at non-singleton dimension 1

In [131]:
preds = labelgrid[..., 0, :]

In [148]:
loss = torch.nn.MSELoss()
inp = torch.randn((16,13,13, 1))
target = torch.randn((16,13,13, 1))
output = loss(inp, target)

In [150]:
output

tensor(1.9788)

In [104]:
ls = torch.tensor([[10, 15],[20, 25],[30, 35],[40, 45],[50, 55]])
h = ls[:,0]
w = ls[:,1]


value = torch.tensor([[0,1],
                      [2,3]])

torch.take(w, value)

        

tensor([[15, 25],
        [35, 45]])

In [101]:
indices = torch.arange(5).repeat(1,5).reshape(5,5)

In [115]:
torch.sqrt(torch.take(ls, indices))

tensor([[3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772]])

In [109]:
(torch.zeros((8,7,7,5,1)) * torch.randn((8,7,7,5))).shape

RuntimeError: The size of tensor a (5) must match the size of tensor b (7) at non-singleton dimension 3

In [122]:
from collections import OrderedDict
from torch import nn
import torch.nn.functional as F
import torch.utils.model_zoo as model_zoo

model_paths = {
    'darknet19': 'https://s3.ap-northeast-2.amazonaws.com/deepbaksuvision/darknet19-deepBakSu-e1b3ec1e.pth'
}

class GlobalAvgPool2d(nn.Module):
    def __init__(self):
        super(GlobalAvgPool2d, self).__init__()

    def forward(self, x):
        N = x.data.size(0)
        C = x.data.size(1)
        H = x.data.size(2)
        W = x.data.size(3)
        x = F.avg_pool2d(x, (H, W))
        x = x.view(N, C)
        return x


class Darknet19(nn.Module):
    def __init__(self, pretrained=True):
        super(Darknet19, self).__init__()

        self.features = nn.Sequential(OrderedDict([
        ('layer1', nn.Sequential(OrderedDict([
            ('conv1_1', nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn1_1', nn.BatchNorm2d(32)),
            ('leaky1_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool1', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer2', nn.Sequential(OrderedDict([
            ('conv2_1', nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn2_1', nn.BatchNorm2d(64)),
            ('leaky2_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool2', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer3', nn.Sequential(OrderedDict([
            ('conv3_1', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_1', nn.BatchNorm2d(128)),
            ('leaky3_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_2', nn.Conv2d(128, 64, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn3_2', nn.BatchNorm2d(64)),
            ('leaky3_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_3', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_3', nn.BatchNorm2d(128)),
            ('leaky3_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool3', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer4', nn.Sequential(OrderedDict([
            ('conv4_1', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_1', nn.BatchNorm2d(256)),
            ('leaky4_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_2', nn.Conv2d(256, 128, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn4_2', nn.BatchNorm2d(128)),
            ('leaky4_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_3', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_3', nn.BatchNorm2d(256)),
            ('leaky4_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool4', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer5', nn.Sequential(OrderedDict([
            ('conv5_1', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_1', nn.BatchNorm2d(512)),
            ('leaky5_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_2', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn5_2', nn.BatchNorm2d(256)),
            ('leaky5_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_3', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_3', nn.BatchNorm2d(512)),
            ('leaky5_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_4', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn5_4', nn.BatchNorm2d(256)),
            ('leaky5_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_5', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_5', nn.BatchNorm2d(512)),
            ('leaky5_5', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool5', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer6', nn.Sequential(OrderedDict([
            ('conv6_1', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_1', nn.BatchNorm2d(1024)),
            ('leaky6_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_2', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn6_2', nn.BatchNorm2d(512)),
            ('leaky6_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_3', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_3', nn.BatchNorm2d(1024)),
            ('leaky6_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_4', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn6_4', nn.BatchNorm2d(512)),
            ('leaky6_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_5', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_5', nn.BatchNorm2d(1024)),
            ('leaky6_5', nn.LeakyReLU(0.1, inplace=True))
        ])))
        ]))

        self.classifier = nn.Sequential(OrderedDict([
        ('conv7_1', nn.Conv2d(1024, 1000, kernel_size=(1, 1), stride=(1, 1))),
        ('globalavgpool', GlobalAvgPool2d()),
        ('softmax', nn.Softmax(dim=1))
        ]))

        # if pretrained:
        #     self.load_state_dict(model_zoo.load_url(model_paths['darknet19'],  progress=True))
        #     print('Model is loaded')

    def forward(self, x):
        for layer in self.features :
            print(layer)
            print('.')
        # out = self.features(x)
        # out = self.classifier(out)
        # return out

In [123]:
model = Darknet19()

In [124]:
model(torch.rand(1))

Sequential(
  (conv1_1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1_1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky1_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv2_1): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2_1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky2_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv3_1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn3_1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky3_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (conv3_2): Conv2d(128, 64, kernel_size=(1, 1), stride=(

In [129]:
torch.zeros_like(torch.randn((8,7,7,5,24))[...,0]).shape

torch.Size([8, 7, 7, 5])