In [1]:
import torch

In [5]:
torch.sigmoid(torch.tensor(0.8))

tensor(0.6900)

In [10]:
torch.tensor([  [], [[1,2],[3,4]] , [[1,2]]         ] )

tensor([], size=(3, 0))

In [7]:
torch.tensor([1,2])

tensor([1, 2])

In [11]:
batch_size = 8
numgrid = 7
numbox = 5
num_classes = 13

labelgrid = torch.randn((batch_size, numgrid, numgrid, numbox, 5 + num_classes))

In [12]:
torch.zeros_like(labelgrid[..., 0]).shape

torch.Size([8, 7, 7, 5])

In [13]:
torch.sigmoid(torch.tensor([[0,0,0,0]]))

tensor([[0.5000, 0.5000, 0.5000, 0.5000]])

In [16]:
# 2x3x3x4=
seq = torch.arange(2*3*3*5*4).contiguous()

grid = seq.reshape(2,3,3,5,4)


In [24]:
grid_mask = torch.zeros((2,3,3,1), dtype = torch.int64)

grid_mask + i

tensor([[[[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          ...,

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]],

          [[0, 0, 0, 0],
           [0, 0, 0, 0],
           [0, 0, 0, 0]]],


         [[[0, 0, 0, 0],
           [0, 

In [35]:
torch.gather(grid, -2, grid_mask.unsqueeze(-1).repeat(1,1,1,1,4))

tensor([[[[[  0,   1,   2,   3]],

          [[ 20,  21,  22,  23]],

          [[ 40,  41,  42,  43]]],


         [[[ 60,  61,  62,  63]],

          [[ 80,  81,  82,  83]],

          [[100, 101, 102, 103]]],


         [[[120, 121, 122, 123]],

          [[140, 141, 142, 143]],

          [[160, 161, 162, 163]]]],



        [[[[180, 181, 182, 183]],

          [[200, 201, 202, 203]],

          [[220, 221, 222, 223]]],


         [[[240, 241, 242, 243]],

          [[260, 261, 262, 263]],

          [[280, 281, 282, 283]]],


         [[[300, 301, 302, 303]],

          [[320, 321, 322, 323]],

          [[340, 341, 342, 343]]]]])

In [19]:
grid[..., 0, :]

tensor([[[[  0,   1,   2,   3],
          [ 20,  21,  22,  23],
          [ 40,  41,  42,  43]],

         [[ 60,  61,  62,  63],
          [ 80,  81,  82,  83],
          [100, 101, 102, 103]],

         [[120, 121, 122, 123],
          [140, 141, 142, 143],
          [160, 161, 162, 163]]],


        [[[180, 181, 182, 183],
          [200, 201, 202, 203],
          [220, 221, 222, 223]],

         [[240, 241, 242, 243],
          [260, 261, 262, 263],
          [280, 281, 282, 283]],

         [[300, 301, 302, 303],
          [320, 321, 322, 323],
          [340, 341, 342, 343]]]])

In [145]:
numgrid = 7

x = torch.arange(numgrid)
y = torch.arange(numgrid)

grid_y, grid_x = torch.meshgrid(x,y, indexing = 'ij')
grid_x = grid_x.expand(8, -1,-1)#.unsqueeze(-1)
grid_y = grid_y.expand(8, -1,-1)#.unsqueeze(-1)

In [147]:
grid_x * torch.randn(8,7,7,1)

RuntimeError: The size of tensor a (8) must match the size of tensor b (7) at non-singleton dimension 1

In [131]:
box1s = labelgrid[..., 0, :]

In [148]:
loss = torch.nn.MSELoss()
inp = torch.randn((16,13,13, 1))
target = torch.randn((16,13,13, 1))
output = loss(inp, target)

In [150]:
output

tensor(1.9788)

In [104]:
ls = torch.tensor([[10, 15],[20, 25],[30, 35],[40, 45],[50, 55]])
h = ls[:,0]
w = ls[:,1]


value = torch.tensor([[0,1],
                      [2,3]])

torch.take(w, value)

        

tensor([[15, 25],
        [35, 45]])

In [101]:
indices = torch.arange(5).repeat(1,5).reshape(5,5)

In [115]:
torch.sqrt(torch.take(ls, indices))

tensor([[3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772],
        [3.1623, 3.8730, 4.4721, 5.0000, 5.4772]])

In [109]:
(torch.zeros((8,7,7,5,1)) * torch.randn((8,7,7,5))).shape

RuntimeError: The size of tensor a (5) must match the size of tensor b (7) at non-singleton dimension 3

In [122]:
from collections import OrderedDict
from torch import nn
import torch.nn.functional as F
import torch.utils.model_zoo as model_zoo

model_paths = {
    'darknet19': 'https://s3.ap-northeast-2.amazonaws.com/deepbaksuvision/darknet19-deepBakSu-e1b3ec1e.pth'
}

class GlobalAvgPool2d(nn.Module):
    def __init__(self):
        super(GlobalAvgPool2d, self).__init__()

    def forward(self, x):
        N = x.data.size(0)
        C = x.data.size(1)
        H = x.data.size(2)
        W = x.data.size(3)
        x = F.avg_pool2d(x, (H, W))
        x = x.view(N, C)
        return x


class Darknet19(nn.Module):
    def __init__(self, pretrained=True):
        super(Darknet19, self).__init__()

        self.features = nn.Sequential(OrderedDict([
        ('layer1', nn.Sequential(OrderedDict([
            ('conv1_1', nn.Conv2d(3, 32, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn1_1', nn.BatchNorm2d(32)),
            ('leaky1_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool1', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer2', nn.Sequential(OrderedDict([
            ('conv2_1', nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn2_1', nn.BatchNorm2d(64)),
            ('leaky2_1', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool2', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer3', nn.Sequential(OrderedDict([
            ('conv3_1', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_1', nn.BatchNorm2d(128)),
            ('leaky3_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_2', nn.Conv2d(128, 64, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn3_2', nn.BatchNorm2d(64)),
            ('leaky3_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv3_3', nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn3_3', nn.BatchNorm2d(128)),
            ('leaky3_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool3', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer4', nn.Sequential(OrderedDict([
            ('conv4_1', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_1', nn.BatchNorm2d(256)),
            ('leaky4_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_2', nn.Conv2d(256, 128, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn4_2', nn.BatchNorm2d(128)),
            ('leaky4_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv4_3', nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn4_3', nn.BatchNorm2d(256)),
            ('leaky4_3', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool4', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer5', nn.Sequential(OrderedDict([
            ('conv5_1', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_1', nn.BatchNorm2d(512)),
            ('leaky5_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_2', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn5_2', nn.BatchNorm2d(256)),
            ('leaky5_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_3', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_3', nn.BatchNorm2d(512)),
            ('leaky5_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_4', nn.Conv2d(512, 256, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn5_4', nn.BatchNorm2d(256)),
            ('leaky5_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv5_5', nn.Conv2d(256, 512, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn5_5', nn.BatchNorm2d(512)),
            ('leaky5_5', nn.LeakyReLU(0.1, inplace=True)),
            ('maxpool5', nn.MaxPool2d(kernel_size=2, stride=2))
        ]))),
        ('layer6', nn.Sequential(OrderedDict([
            ('conv6_1', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_1', nn.BatchNorm2d(1024)),
            ('leaky6_1', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_2', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=0, bias=False)),
            ('bn6_2', nn.BatchNorm2d(512)),
            ('leaky6_2', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_3', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_3', nn.BatchNorm2d(1024)),
            ('leaky6_3', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_4', nn.Conv2d(1024, 512, kernel_size=1, stride=1, padding=1, bias=False)),
            ('bn6_4', nn.BatchNorm2d(512)),
            ('leaky6_4', nn.LeakyReLU(0.1, inplace=True)),
            ('conv6_5', nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)),
            ('bn6_5', nn.BatchNorm2d(1024)),
            ('leaky6_5', nn.LeakyReLU(0.1, inplace=True))
        ])))
        ]))

        self.classifier = nn.Sequential(OrderedDict([
        ('conv7_1', nn.Conv2d(1024, 1000, kernel_size=(1, 1), stride=(1, 1))),
        ('globalavgpool', GlobalAvgPool2d()),
        ('softmax', nn.Softmax(dim=1))
        ]))

        # if pretrained:
        #     self.load_state_dict(model_zoo.load_url(model_paths['darknet19'],  progress=True))
        #     print('Model is loaded')

    def forward(self, x):
        for layer in self.features :
            print(layer)
            print('.')
        # out = self.features(x)
        # out = self.classifier(out)
        # return out

In [123]:
model = Darknet19()

In [124]:
model(torch.rand(1))

Sequential(
  (conv1_1): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn1_1): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky1_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv2_1): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn2_1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky2_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (maxpool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
.
Sequential(
  (conv3_1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (bn3_1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (leaky3_1): LeakyReLU(negative_slope=0.1, inplace=True)
  (conv3_2): Conv2d(128, 64, kernel_size=(1, 1), stride=(

In [129]:
torch.zeros_like(torch.randn((8,7,7,5,24))[...,0]).shape

torch.Size([8, 7, 7, 5])

In [3]:
import torch

a = torch.tensor([1]).numpy().item()

a

1

In [6]:
import numpy as np
np.maximum(torch.tensor([1,2,3]), torch.tensor([1,2,3]))

tensor([1, 2, 3])

In [98]:
def IoU(box1, box2) :
    # box = [x,y,w,h]

    def box_area(box) :
        return box[2] * box[3]
    
    box1_area = box_area(box1.T)
    box2_area = box_area(box2.T)

    box1_w = box1[..., 2:3]
    box1_h = box1[..., 3:4]
    box2_w = box2[..., 2:3]
    box2_h = box2[..., 3:4]
    box1_xmin = box1[..., 0:1] - box1_w / 2
    box1_ymin = box1[..., 1:2] - box1_h / 2
    box1_xmax = box1[..., 0:1] + box1_w / 2
    box1_ymax = box1[..., 1:2] + box1_w / 2

    box2_xmin = box2[..., 0:1] - box2_w / 2
    box2_ymin = box2[..., 1:2] - box2_h / 2
    box2_xmax = box2[..., 0:1] + box2_w / 2
    box2_ymax = box2[..., 1:2] + box2_w / 2
    
    box1_topleft = torch.cat([box1_xmin, box1_ymin], axis = -1)
    box2_topleft = torch.cat([box2_xmin, box2_ymin], axis = -1)

    box1_bottomright = torch.cat([box1_xmax, box1_ymax], axis = -1)
    box2_bottomright = torch.cat([box2_xmax, box2_ymax], axis = -1)

    top_left = torch.max(box1_topleft[:,None, :], box2_topleft)
    bottom_right = torch.min(box1_bottomright[:, None, :], box2_bottomright)



    area_inter = torch.prod(
        torch.clip(bottom_right - top_left, min = 0 , max = None), -1)

    return area_inter / (box1_area[:, None] + box2_area - area_inter + 1e-9)

In [2]:
import sys
sys.path.append('./YOLOv2')
from YOLOv2.model import Yolov2



c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


In [11]:
model.load_from_checkpoint(in_channels = 3, anchorbox = [[0.57273, 0.677385], [1.87446, 2.06253], [3.33843, 5.47434], [7.88282, 3.52778], [9.77052, 9.16828]], num_grid = 13, num_classes = 13,
            checkpoint_path = 'YOLOv2/outputs/2023-04-16/12-36-28/tensorboard/yolov2-epoch=72-val_loss=3863.54.ckpt')

c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


RuntimeError: Error(s) in loading state_dict for Yolov2:
	While copying the parameter named "yolo_loss.grid_x", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).
	While copying the parameter named "yolo_loss.grid_y", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).

In [15]:
import torch

model = Yolov2(in_channels = 3, anchorbox = [[0.57273, 0.677385], [1.87446, 2.06253], [3.33843, 5.47434], [7.88282, 3.52778], [9.77052, 9.16828]], num_grid = 13, num_classes = 13)

model.yolo_loss.grid_x = model.yolo_loss.grid_x.contiguous()
model.yolo_loss.grid_y = model.yolo_loss.grid_y.contiguous()

weight = torch.load('YOLOv2/outputs/2023-04-16/12-36-28/tensorboard/yolov2-epoch=72-val_loss=3863.54.ckpt')
model.load_state_dict(weight['state_dict'])

c:\Users\user\Desktop\projects\object_detection\./YOLOv2\loss.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('anchorbox', torch.tensor(anchorbox))


RuntimeError: Error(s) in loading state_dict for Yolov2:
	While copying the parameter named "yolo_loss.grid_x", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).
	While copying the parameter named "yolo_loss.grid_y", whose dimensions in the model are torch.Size([13, 13]) and whose dimensions in the checkpoint are torch.Size([13, 13]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).

In [19]:
import sys
sys.path.append('YOLOv2')
from YOLOv2.data import BDDDataModule

BDDDataModule()


[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


     -------------------------------------- 154.5/154.5 kB 9.0 MB/s eta 0:00:00
     -------------------------------------- 117.0/117.0 kB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 79.5/79.5 kB ? eta 0:00:00
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144578 sha256=0da2085491a6d9450add46c9e94525d78ec7272bd81250e788034e3c6bc6dca4
  Stored in directory: c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\48\6a\c2\acb58c7afdf57e4cddf5e1513f5a2d62aa8e98f82a00c76d7c
Successfully built antlr4-python3-runtime


TypeError: BDDDataModule.__init__() missing 1 required positional argument: 'cfg'

In [49]:
loss = torch.nn.BCEWithLogitsLoss()

inp = torch.tensor([1, 1, 1, 1]).float()
target = torch.tensor([0, 1, 0, 1]).float()
inp = inp * target

loss(inp, target)

tensor(0.5032)

In [ ]:


def kmean_anchors(path='./data/coco128.yaml', n=9, img_size=640, thr=4.0, gen=1000, verbose=True):
    """ Creates kmeans-evolved anchors from training dataset
        Arguments:
            path: path to dataset *.yaml, or a loaded dataset
            n: number of anchors
            img_size: image size used for training
            thr: anchor-label wh ratio threshold hyperparameter hyp['anchor_t'] used for training, default=4.0
            gen: generations to evolve anchors using genetic algorithm
            verbose: print all results
        Return:
            k: kmeans evolved anchors
        Usage:
            from utils.general import *; _ = kmean_anchors()
    """
    thr = 1. / thr

    def metric(k, wh):  # compute metrics
        r = wh[:, None] / k[None]
        x = torch.min(r, 1. / r).min(2)[0]  # ratio metric
        # x = wh_iou(wh, torch.tensor(k))  # iou metric
        return x, x.max(1)[0]  # x, best_x

    def anchor_fitness(k):  # mutation fitness
        _, best = metric(torch.tensor(k, dtype=torch.float32), wh)
        return (best * (best > thr).float()).mean()  # fitness

    def print_results(k):
        k = k[np.argsort(k.prod(1))]  # sort small to large
        x, best = metric(k, wh0)
        bpr, aat = (best > thr).float().mean(), (x > thr).float().mean() * n  # best possible recall, anch > thr
        print('thr=%.2f: %.4f best possible recall, %.2f anchors past thr' % (thr, bpr, aat))
        print('n=%g, img_size=%s, metric_all=%.3f/%.3f-mean/best, past_thr=%.3f-mean: ' %
              (n, img_size, x.mean(), best.mean(), x[x > thr].mean()), end='')
        for i, x in enumerate(k):
            print('%i,%i' % (round(x[0]), round(x[1])), end=',  ' if i < len(k) - 1 else '\n')  # use in *.cfg
        return k

    if isinstance(path, str):  # *.yaml file
        with open(path) as f:
            data_dict = yaml.load(f, Loader=yaml.FullLoader)  # model dict
        from utils.datasets import LoadImagesAndLabels
        dataset = LoadImagesAndLabels(data_dict['train'], augment=True, rect=True)
    else:
        dataset = path  # dataset

    # Get label wh
    shapes = img_size * dataset.shapes / dataset.shapes.max(1, keepdims=True)
    wh0 = np.concatenate([l[:, 3:5] * s for s, l in zip(shapes, dataset.labels)])  # wh

    # Filter
    i = (wh0 < 3.0).any(1).sum()
    if i:
        print('WARNING: Extremely small objects found. '
              '%g of %g labels are < 3 pixels in width or height.' % (i, len(wh0)))
    wh = wh0[(wh0 >= 2.0).any(1)]  # filter > 2 pixels

    # Kmeans calculation
    print('Running kmeans for %g anchors on %g points...' % (n, len(wh)))
    s = wh.std(0)  # sigmas for whitening
    k, dist = kmeans(wh / s, n, iter=30)  # points, mean distance
    k *= s
    wh = torch.tensor(wh, dtype=torch.float32)  # filtered
    wh0 = torch.tensor(wh0, dtype=torch.float32)  # unfiltered
    k = print_results(k)

    # Plot
    # k, d = [None] * 20, [None] * 20
    # for i in tqdm(range(1, 21)):
    #     k[i-1], d[i-1] = kmeans(wh / s, i)  # points, mean distance
    # fig, ax = plt.subplots(1, 2, figsize=(14, 7))
    # ax = ax.ravel()
    # ax[0].plot(np.arange(1, 21), np.array(d) ** 2, marker='.')
    # fig, ax = plt.subplots(1, 2, figsize=(14, 7))  # plot wh
    # ax[0].hist(wh[wh[:, 0]<100, 0],400)
    # ax[1].hist(wh[wh[:, 1]<100, 1],400)
    # fig.tight_layout()
    # fig.savefig('wh.png', dpi=200)

    # Evolve
    npr = np.random
    f, sh, mp, s = anchor_fitness(k), k.shape, 0.9, 0.1  # fitness, generations, mutation prob, sigma
    pbar = tqdm(range(gen), desc='Evolving anchors with Genetic Algorithm')  # progress bar
    for _ in pbar:
        v = np.ones(sh)
        while (v == 1).all():  # mutate until a change occurs (prevent duplicates)
            v = ((npr.random(sh) < mp) * npr.random() * npr.randn(*sh) * s + 1).clip(0.3, 3.0)
        kg = (k.copy() * v).clip(min=2.0)
        fg = anchor_fitness(kg)
        if fg > f:
            f, k = fg, kg.copy()
            pbar.desc = 'Evolving anchors with Genetic Algorithm: fitness = %.4f' % f
            if verbose:
                print_results(k)

    return print_results(k)


In [52]:
10 / 416

373 / 416, 326 / 416

(0.8966346153846154, 0.7836538461538461)

In [3]:
import torch
import numpy as np

def IoU(box1, box2) :
    # box = [x,y,w,h]

    
    box1_w = box1[..., 2:3]
    box1_h = box1[..., 3:4]
    box2_w = box2[..., 2:3]
    box2_h = box2[..., 3:4]

    box1_area = box1_w * box1_h
    box2_area = box2_w * box2_h

    box1_xmin = box1[..., 0:1] - box1_w / 2
    box1_ymin = box1[..., 1:2] - box1_h / 2
    box1_xmax = box1[..., 0:1] + box1_w / 2
    box1_ymax = box1[..., 1:2] + box1_w / 2

    box2_xmin = box2[..., 0:1] - box2_w / 2
    box2_ymin = box2[..., 1:2] - box2_h / 2
    box2_xmax = box2[..., 0:1] + box2_w / 2
    box2_ymax = box2[..., 1:2] + box2_w / 2
    
    box1_topleft = torch.cat([box1_xmin, box1_ymin], axis = -1)
    box2_topleft = torch.cat([box2_xmin, box2_ymin], axis = -1)

    box1_bottomright = torch.cat([box1_xmax, box1_ymax], axis = -1)
    box2_bottomright = torch.cat([box2_xmax, box2_ymax], axis = -1)

    top_left = torch.max(box1_topleft, box2_topleft)
    bottom_right = torch.min(box1_bottomright, box2_bottomright)



    area_inter = torch.prod(
        torch.clip(bottom_right - top_left, min = 0 , max = None), -1).unsqueeze(-1)
    


    return area_inter / (box1_area + box2_area - area_inter + 1e-9)


In [35]:
def vectorized_IoU(boxes_a, boxes_b) :
    def box_area(box) :
        return box[2] * box[3]

    area_a = box_area(boxes_a.T)
    area_b = box_area(boxes_b.T)
    
    boxes_a_xmin = boxes_a[..., 0:1] - boxes_a[..., 2:3] / 2
    boxes_a_xmax = boxes_a[..., 0:1] + boxes_a[..., 2:3] / 2
    boxes_a_ymin = boxes_a[..., 1:2] - boxes_a[..., 3:4] / 2
    boxes_a_ymax = boxes_a[..., 1:2] + boxes_a[..., 3:4] / 2

    boxes_b_xmin = boxes_b[..., 0:1] - boxes_b[..., 2:3] / 2
    boxes_b_xmax = boxes_b[..., 0:1] + boxes_b[..., 2:3] / 2
    boxes_b_ymin = boxes_b[..., 1:2] - boxes_b[..., 3:4] / 2
    boxes_b_ymax = boxes_b[..., 1:2] + boxes_b[..., 3:4] / 2

    boxes_a_topleft = np.concatenate([boxes_a_xmin, boxes_a_ymin], axis = -1)
    boxes_a_bottomright = np.concatenate([boxes_a_xmax, boxes_a_ymax], axis = -1)

    boxes_b_topleft = np.concatenate([boxes_b_xmin, boxes_b_ymin], axis = -1)
    boxes_b_bottomright = np.concatenate([boxes_b_xmax, boxes_b_ymax], axis = -1)
    
    top_left = np.maximum(boxes_a_topleft[..., None, :], boxes_b_topleft )
    bottom_right = np.minimum(boxes_a_bottomright[..., None, :], boxes_b_bottomright)

    area_inter = np.prod(
        np.clip(bottom_right - top_left, a_min = 0, a_max = None), -1
    )

    return area_inter / (area_a[..., None] + area_b - area_inter )


In [71]:
def nms(predictions, confidence_threshold: float , iou_threshold: float) :
    '''
    vectorize nms
    reference : https://blog.roboflow.com/how-to-code-non-maximum-suppression-nms-in-plain-numpy/
    '''
    predictions = np.array(predictions)
    rows, columns = predictions.shape
    assert columns == 6, 'bbox should contain [confidence_score, x_center, y_center, w, h, pred_class]'
    
    sort_index = np.flip(predictions[:,0].argsort())
    predictions = predictions[sort_index]

    boxes = predictions[:, 1:5]
    categories = predictions[:, -1]
    ious = vectorized_IoU(torch.tensor(boxes), torch.tensor(boxes)).detach().cpu().numpy()
    ious = ious - np.eye(rows)
    keep = predictions[:, 0] > confidence_threshold # np.ones(rows, dtype = bool)

    for index, (iou, category) in enumerate(zip(ious, categories)) :
        if not keep[index] :
            continue
    
        condition = (iou > iou_threshold) & (categories == category)
        keep = keep & ~condition

    return predictions[keep[sort_index.argsort()]]


In [210]:
bboxes = torch.tensor([
    [0.9, .2, .4, .2, .2, 1], # 0.1, 0.3, 0.1, 0.3
    [0.8, .6, .4, .2, .2, 1], # 0.5, 0.3, 0.7, 0.5
    [0.7, .3, .3, .2, .2, 1], # 0.2, 0.2, 0.4, 0.4
    [0.8, .75, .3, .3,.2, 1]  # 0.6, 0.2, 0.9, 0.4
])




vectorized_IoU(bboxes[...,1:5], bboxes[..., 1:5])

tensor([[1.0000, 0.0000, 0.1429, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.1111],
        [0.1429, 0.0000, 1.0000, 0.0000],
        [0.0000, 0.1111, 0.0000, 1.0000]])

In [105]:
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [211]:
def soft_nms(predictions, confidence_threshold, sigma = 0.5) :
    '''
    vectorize soft_nms
    reference : https://blog.roboflow.com/how-to-code-non-maximum-suppression-nms-in-plain-numpy/
    weight confidence scores with overlapped boxes
    '''
    predictions = np.array(predictions)
    rows, columns = predictions.shape
    assert columns == 6, 'bbox should contain [confidence_score, x_center, y_center, w, h, pred_class]'
    
    sort_index = np.flip(predictions[:,0].argsort())
    predictions = predictions[sort_index]

    boxes = predictions[:, 1:5]
    categories = predictions[:, -1]
    ious = vectorized_IoU(torch.tensor(boxes), torch.tensor(boxes)).detach().cpu().numpy()
    ious = ious - np.eye(rows)
    

    weight = np.exp(- np.tril(ious) ** 2 / sigma)
    confidence_weight = np.multiply.reduce(weight, -1)
    predictions[..., 0] *= confidence_weight

    keep = predictions[..., 0] > confidence_threshold

    return predictions[keep]


In [212]:
soft_nms(bboxes, confidence_threshold= 0.5)

array([[0.9      , 0.2      , 0.4      , 0.2      , 0.2      , 1.       ],
       [0.8      , 0.75     , 0.3      , 0.3      , 0.2      , 1.       ],
       [0.7804888, 0.6      , 0.4      , 0.2      , 0.2      , 1.       ],
       [0.6720038, 0.3      , 0.3      , 0.2      , 0.2      , 1.       ]],
      dtype=float32)

In [271]:
def soft_nms_pytorch(predictions, sigma=0.5, thresh=0.001, cuda=0):
    """
    from https://github.com/DocF/Soft-NMS/blob/master/softnms_pytorch.py
    Build a pytorch implement of Soft NMS algorithm.
    # Augments
        predictions:        boxes coordinate tensor (format:[confidence_score, x_center, y_center, w, h, category])
        sigma:       variance of Gaussian function
        thresh:      score thresh
        cuda:        CUDA flag
    # Return
        the index of the selected boxes
    """

    # Indexes concatenate boxes with the last column
    N = predictions.shape[0]
    if cuda:
        indexes = torch.arange(0, N, dtype=torch.float).cuda().view(N, 1)
    else:
        indexes = torch.arange(0, N, dtype=torch.float).view(N, 1)
    predictions = torch.cat((predictions, indexes), dim=1)

    # The order of boxes coordinate is [y1,x1,y2,x2]
    y1 = predictions[..., 1:2] - predictions[..., 3:4] / 2
    x1 = predictions[..., 0:1] - predictions[..., 2:3] / 2
    y2 = predictions[..., 1:2] + predictions[..., 3:4] / 2
    x2 = predictions[..., 0:1] + predictions[..., 2:3] / 2

    x1y1x2y2 = torch.cat([x1,y1,x2,y2], axis = -1)
    
    scores = predictions[..., 0]
    areas = (x2 - x1 + 1) * (y2 - y1 + 1)

    for i in range(N):
        # intermediate parameters for later parameters exchange
        tscore = scores[i].clone()
        pos = i + 1

        if i != N - 1:
            maxscore, maxpos = torch.max(scores[pos:], dim=0)
            if tscore < maxscore:
                predictions[i], predictions[maxpos.item() + i + 1] = predictions[maxpos.item() + i + 1].clone(), predictions[i].clone()
                scores[i], scores[maxpos.item() + i + 1] = scores[maxpos.item() + i + 1].clone(), scores[i].clone()
                areas[i], areas[maxpos + i + 1] = areas[maxpos + i + 1].clone(), areas[i].clone()

        # IoU calculate
        yy1 = np.maximum(x1y1x2y2[i, 1].to("cpu").numpy(), x1y1x2y2[pos:, 1].to("cpu").numpy())
        xx1 = np.maximum(x1y1x2y2[i, 0].to("cpu").numpy(), x1y1x2y2[pos:, 0].to("cpu").numpy())
        yy2 = np.minimum(x1y1x2y2[i, 3].to("cpu").numpy(), x1y1x2y2[pos:, 3].to("cpu").numpy())
        xx2 = np.minimum(x1y1x2y2[i, 2].to("cpu").numpy(), x1y1x2y2[pos:, 2].to("cpu").numpy())
        
        w = np.maximum(0.0, xx2 - xx1 + 1)
        h = np.maximum(0.0, yy2 - yy1 + 1)
        inter = torch.tensor(w * h).cuda() if cuda else torch.tensor(w * h)
        ovr = torch.div(inter, (areas[i] + areas[pos:] - inter))

        # Gaussian decay
        weight = torch.exp(-(ovr * ovr) / sigma)
        scores[pos:] = weight * scores[pos:]

    # select the boxes and keep the corresponding indexes
    keep = predictions[:, 4][scores > thresh].int()

    return keep


In [272]:
coco_bboxes = torch.tensor([
    [1, .1, .2, .3, .4, 1], # 0.1, 0.2, 0.3, 0.4
    [0.5, .5, .3, .7, .5, 1], # 0.5, 0.3, 0.7, 0.5
    [0.5, .2, .2, .4, .4, 1], # 0.2, 0.2, 0.4, 0.4
    [0.7, .6, .2, .9,.4, 1]  # 0.6, 0.2, 0.9, 0.4
])

bboxes = torch.tensor([
    [1, .2, .4, .2, .2, 1], # 0.1, 0.3, 0.1, 0.3
    [0.5, .6, .4, .2, .2, 1], # 0.5, 0.3, 0.7, 0.5
    [0.5, .3, .3, .2, .2, 1], # 0.2, 0.2, 0.4, 0.4
    [0.7, .75, .3, .3,.2, 1]  # 0.6, 0.2, 0.9, 0.4
])




In [273]:
soft_nms_pytorch(bboxes)

RuntimeError: expand(torch.FloatTensor{[3, 3]}, size=[3]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

In [236]:
boxes = torch.tensor([[200, 200, 400, 400],
                          [220, 220, 420, 420],
                          [200, 240, 400, 440],
                          [240, 200, 440, 400],
                          [1, 1, 2, 2]])




boxscores = torch.tensor([0.8, 0.7, 0.6, 0.5, 0.9], dtype=torch.float)




keep, scores = soft_nms_pytorch(boxes, boxscores, thresh = 0.81)

scores

tensor([0.9000, 0.8000, 0.2762, 0.0970, 0.0517])

In [145]:
soft_nms(bboxes, confidence_threshold = 0.5)

array([[1.  , 0.2 , 0.4 , 0.2 , 0.2 , 1.  ],
       [0.7 , 0.75, 0.3 , 0.3 , 0.2 , 1.  ]], dtype=float32)

In [242]:
def box_iou_batch(boxes_a, boxes_b):
    boxes_a = np.array(boxes_a)
    boxes_b = np.array(boxes_b)
    def box_area(box):
        return (box[2] - box[0]) * (box[3] - box[1])

    area_a = box_area(boxes_a.T)
    area_b = box_area(boxes_b.T)

    top_left = np.maximum(boxes_a[..., :2], boxes_b[..., :2])
    bottom_right = np.minimum(boxes_a[..., None, 2:], boxes_b[..., 2:])

    

    area_inter = np.prod(
    	np.clip(bottom_right - top_left, a_min=0, a_max=None), axis = -1)
        
    return area_inter / (area_a[..., None] + area_b - area_inter)

In [243]:
box_iou_batch(boxes,boxes)

array([[1.00000000e+00, 6.80672269e-01, 6.66666667e-01, 6.66666667e-01,
        2.50000000e-05],
       [1.00000000e+00, 1.00000000e+00, 8.18181818e-01, 8.18181818e-01,
        2.50000000e-05],
       [1.00000000e+00, 8.18181818e-01, 1.00000000e+00, 6.66666667e-01,
        2.50000000e-05],
       [1.00000000e+00, 8.18181818e-01, 6.66666667e-01, 1.00000000e+00,
        2.50000000e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00]])

In [253]:
boxes_confidence = torch.tensor([[0.8, 200, 200, 400, 400],
                                    [0.7, 220, 220, 420, 420],
                                    [0.6, 200, 240, 400, 440],
                                    [0.5, 240, 200, 440, 400],
                                    [0.6, 1, 1, 2, 2]], dtype = torch.float32)



In [250]:
sigma = 0.5

boxes_confidence = np.array(boxes_confidence)
boxscores = boxes_confidence[:,0]
sort_index = np.flip(boxscores.argsort())
boxes_confidence = boxes_confidence[sort_index]
boxes = boxes_confidence[..., 1:5]

ious = box_iou_batch(boxes,boxes)
ious = ious - np.eye(5)
weight = np.exp(- np.tril(ious) ** 2 / sigma)
confidence_weight = np.multiply.reduce(weight, -1)
boxscores *= confidence_weight

In [251]:
boxscores

array([0.9       , 0.8       , 0.0947347 , 0.02128679, 0.00729272],
      dtype=float32)

In [252]:
scores

tensor([0.9000, 0.8000, 0.2762, 0.0970, 0.0517])